export enum RPCCommand {
  DISPATCH = "DISPATCH",
  AUTHORIZE = "AUTHORIZE",
  AUTHENTICATE = "AUTHENTICATE",

  GET_GUILD = "GET_GUILD",
  GET_GUILDS = "GET_GUILDS",

  GET_CHANNEL = "GET_CHANNEL",
  GET_CHANNELS = "GET_CHANNELS",

  SUBSCRIBE = "SUBSCRIBE",
  UNSUBSCRIBE = "UNSUBSCRIBE",

  SET_ACTIVITY = "SET_ACTIVITY",
  SEND_ACTIVITY_JOIN_INVITE = "SEND_ACTIVITY_JOIN_INVITE",
  CLOSE_ACTIVITY_REQUEST = "CLOSE_ACTIVITY_REQUEST",

  SELECT_VOICE_CHANNEL = "SELECT_VOICE_CHANNEL",
  GET_SELECTED_VOICE_CHANNEL = "GET_SELECTED_VOICE_CHANNEL",

  SET_VOICE_SETTINGS = "SET_VOICE_SETTINGS",
  GET_VOICE_SETTINGS = "GET_VOICE_SETTINGS",
  SET_USER_VOICE_SETTINGS = "SET_USER_VOICE_SETTINGS",
}