export enum RPCEvent {
  READY = "READY",
  ERROR = "ERROR",

  CURRENT_USER_UPDATE = "CURRENT_USER_UPDATE",
  RELATIONSHIP_UPDATE = "RELATIONSHIP_UPDATE",

  GUILD_STATUS = "GUILD_STATUS",
  GUILD_CREATE = "GUILD_CREATE",

  CHANNEL_CREATE = "CHANNEL_CREATE",

  VOICE_CHANNEL_SELECT = "VOICE_CHANNEL_SELECT",
  VOICE_STATE_CREATE = "VOICE_STATE_CREATE",
  VOICE_STATE_UPDATE = "VOICE_STATE_UPDATE",
  VOICE_STATE_DELETE = "VOICE_STATE_DELETE",

  VOICE_SETTINGS_UPDATE = "VOICE_SETTINGS_UPDATE",
  VOICE_CONNECTION_STATUS = "VOICE_CONNECTION_STATUS",

  SPEAKING_START = "SPEAKING_START",
  SPEAKING_STOP = "SPEAKING_STOP",

  MESSAGE_CREATE = "MESSAGE_CREATE",
  MESSAGE_UPDATE = "MESSAGE_UPDATE",
  MESSAGE_DELETE = "MESSAGE_DELETE",

  NOTIFICATION_CREATE = "NOTIFICATION_CREATE",

  ACTIVITY_JOIN = "ACTIVITY_JOIN",
  ACTIVITY_SPECTATE = "ACTIVITY_SPECTATE",
  ACTIVITY_JOIN_REQUEST = "ACTIVITY_JOIN_REQUEST",
  ACTIVITY_INVITE = "ACTIVITY_INVITE",

  ENTITLEMENT_CREATE = "ENTITLEMENT_CREATE",
  ENTITLEMENT_DELETE = "ENTITLEMENT_DELETE",
}